server:
  port: ${SPRING_API_GATEWAY_PORT}
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: ${SPRING_UR_SERVICE_URL}
              predicates:
                - Path=/users/**
              filters:
                - StripPrefix=1
security:
  jwt:
    access-token:
      secret-key: ${JWT_ACCESS_TOKEN_SECRET_KEY}

