spring:
  application:
    name: hcp-compute-service
  lifecycle:
    timeout-per-shutdown-phase: 20s
  jackson:
    time-zone: Asia/Seoul
  datasource:
    url: ${SPRING_CP_JDBC_URL}
    username: ${SPRING_CP_DB_USER}
    password: ${SPRING_CP_DB_PASSWORD}
    driver-class-name: ${SPRING_CP_DB_DRIVER}
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: none # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        auto_quote_keyword: false
        globally_quoted_identifiers: false
        format_sql: false     # 쿼리 로그 포맷 (정렬)
        show_sql: false       # 쿼리 로그 출력
        jdbc:
          time_zone: Asia/Seoul
  kafka:
    bootstrap-servers: ${SPRING_CP_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: compute-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        max.poll.records: 50
        max.poll.interval.ms: 300000
    producer:
      acks: all
      retries: 10
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
      linger-ms: 5
      batch-size: 32768
      compression-type: lz4
      delivery-timeout-ms: 120000
      request-timeout-ms: 30000
server:
  shutdown: graceful # graceful shutdown
  port: ${SPRING_CP_PORT}
security:
  allowed-api-paths:
    - /actuator/health/**
    - /actuator/info/**
    - /actuator/healt
outbox:
  poll-interval-ms: 2000
  batch-size: 200
  kafka-ack-timeout-ms: 5000
websocket:
  orchestrator-worker:
    url: ${SPRING_WK_SERVICE_WS_URL}/ws/internal/computes






