spring:
  config:
    import: optional:file:.env.local[.properties]
security:
  allowed-origins:
    - http://localhost:3000
  jwt:
    access-token:
      expire-time: 300 #5분
  refresh-token:
    expire-time: 3600 #1시간
    secure: false

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE