spring:
  application:
    name: hcp-user-service
  lifecycle:
    timeout-per-shutdown-phase: 20s
  jackson:
    time-zone: Asia/Seoul
  datasource:
    url: ${SPRING_UR_JDBC_URL}
    username: ${SPRING_UR_DB_USER}
    password: ${SPRING_UR_DB_PASSWORD}
    driver-class-name: ${SPRING_UR_DB_DRIVER}
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: none # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        auto_quote_keyword: false
        globally_quoted_identifiers: false
        format_sql: true     # 쿼리 로그 포맷 (정렬)
        show_sql: true       # 쿼리 로그 출력
        jdbc:
          time_zone: Asia/Seoul
server:
  shutdown: graceful # graceful shutdown
  port: ${SPRING_UR_PORT}
security:
  allowed-api-paths:
    - /v1/auth/login
    - /v1/auth/token/refresh
    - /v1/user-management/register
  jwt:
    refresh-token:
      secure: false
      cookie-name: RTK
      expire-time: 604800 # 일



